In [1]:
%matplotlib inline
from __future__ import print_function
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Input
from keras.layers import LSTM, SpatialDropout1D 
from sklearn.model_selection import train_test_split
import csv
import keras
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint
import os
#from getcpuinfo import cpuinfo
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import requests
from apscheduler.schedulers.background import BackgroundScheduler
import datetime
from keras import regularizers

Using TensorFlow backend.


In [2]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))
from apis.getcpuinfo import cpuinfo 

In [3]:
from sklearn.metrics import accuracy_score

In [4]:
def getTrainedLSTMModel(maxLengthParam):
    
    model = Sequential()
    
    #model.add(SpatialDropout1D(0.3))
    
    model.add(LSTM((50),dropout = 0.3,batch_input_shape = (None,maxLengthParam,1), return_sequences = True))
    
    model.add(Dense(50, activation = 'tanh'))
    
    #model.add(SpatialDropout1D(0.3))
    
    model.add(LSTM(25,return_sequences = False))
    
    model.add(Dense(3, activation='softmax'))
    
    model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])
    
    if os.path.isfile("LSTMBestWeights.hdf5"):
        
        #print("Hey")
        
        model.load_weights("LSTMBestWeights.hdf5")
        
        return model
    else:
        
        print("Unable to find trained model")
        
        return -1;
    
    
def getTrained3OuptutModel(maxLengthParam):
    
    model = Sequential()
    
    #model.add(SpatialDropout1D(0.3))
    
    model.add(Flatten(batch_input_shape = (None,maxLengthParam,1)))
    
    model.add(Dense(50, activation = "relu"))
    
    model.add(Dropout(0.3, noise_shape=None, seed=None))
    
    model.add(Dense(25, activation = 'relu'))
    
    model.add(Dropout(0.3, noise_shape=None, seed=None))
    
    #model.add(SpatialDropout1D(0.3))
    
    model.add(Dense(12,activation = 'relu'))
    
    model.add(Dropout(0.3, noise_shape=None, seed=None))
    
    model.add(Dense(6,activation = 'relu'))
    
    model.add(Dropout(0.3, noise_shape=None, seed=None))
    
    model.add(Dense(3, activation='softmax'))
    
    model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])
    
    if os.path.isfile("3OutputDNNBestWeights.hdf5"):
        
        #print("Hey")
        
        model.load_weights("3OutputDNNBestWeights.hdf5")
        
        print("Returning Trained Model")
        
        return model
    else:
        
        print("Unable to find trained model")
        
        return -1;
    
def getTrainedRL3OutputDNN(historyParam):
    
    usageInputLayer = keras.layers.Input(shape=(historyParam,1))
    
    flattened_layer = keras.layers.Flatten()(usageInputLayer)
    
    '''fullyConnected_0 = keras.layers.Dense(125, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(flattened_layer)'''
    
    fullyConnected_1 = keras.layers.Dense(50, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(flattened_layer)
    
    #drop1 = keras.layers.Dropout(0.25)(fullyConnected_1)
    
    fullyConnected_2 = keras.layers.Dense(50, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(fullyConnected_1)
    
    #drop2 = keras.layers.Dropout(0.25)(fullyConnected_2)
    
    fullyConnected_3 = keras.layers.Dense(50, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(fullyConnected_2)
    
    fullyConnected_4 = keras.layers.Dense(25, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(fullyConnected_3)
    
    fullyConnected_5 = keras.layers.Dense(12, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(fullyConnected_4)
    
    fullyConnected_6 = keras.layers.Dense(6, activation = 'relu',
                    kernel_initializer='he_normal',kernel_regularizer=regularizers.l2(0.1))(fullyConnected_5)
    
    softmax_output = keras.layers.Dense(3,activation='softmax',kernel_initializer='he_normal')(fullyConnected_6)
    
    predictionModel = keras.models.Model(inputs=usageInputLayer,outputs=softmax_output)
    
    if os.path.isfile("3OutputRLV4BestWeights.hdf5"):
        
        #print("Hey")
        
        predictionModel.load_weights("3OutputRLV4BestWeights.hdf5")
        
        print("Returning Trained Model")
        
        return predictionModel
    
    else:
        
        print("Unable to find trained model")
        
        return -1;
    
def getTrainedRLLSTM(historyParam):
    
    usageInputLayer = keras.layers.Input(shape=(historyParam,1))
    
    #flattened_layer = keras.layers.Flatten()(usageInputLayer)
    
    LSTM_1 = keras.layers.LSTM((50), return_sequences = True)(usageInputLayer)
    
    full_connect_2 = keras.layers.Dense(25, activation = 'relu',kernel_initializer='he_normal')(LSTM_1)
    
    LSTM_3 = keras.layers.LSTM(25, return_sequences = False)(full_connect_2)
    
    full_connect_3 = keras.layers.Dense(12, activation = 'relu',kernel_initializer='he_normal')(LSTM_3)
    
    full_connect_4 = keras.layers.Dense(6, activation = 'relu',kernel_initializer='he_normal')(full_connect_3)
    
    softmax_output = keras.layers.Dense(3,activation='softmax',kernel_initializer='he_normal')(full_connect_4)
    
    predictionModel = keras.models.Model(inputs=usageInputLayer,outputs=softmax_output)
    
    if os.path.isfile("LSTMV3RLBestWeights.hdf5"):
        
        #print("Hey")
        
        predictionModel.load_weights("LSTMV3RLBestWeights.hdf5")
        
        print("Returning Trained Model")
        
        return predictionModel
    else:
        
        print("Unable to find trained model")
        
        return -1

In [5]:
def appendToList(oldList,newList,maxLength):
    
    #append to the new entries
    #oldList = np.insert(oldList,0,np.array([newList]),axis = 0)
    oldList = np.append(oldList,np.array([newList]),axis = 0)
    #Remove oldest row if there are more than 50 entries
    if(oldList.shape[0]>maxLength):
        oldList = oldList[1:,:]
    #print(oldList)
    return oldList

def getPredictionsForOneTimeStep(model,usageList,maxLengthParam):
    
    currUsageList = cpuinfo()
    
    updatedList = appendToList(usageList,currUsageList,maxLengthParam)
    
    predictions = []
    
    predDict = {0:0,1:1,2:-1}
    
    for i in range(updatedList.shape[1]):
        
        if updatedList.shape[0]==maxLengthParam:
            
            modelOutput = model.predict(np.expand_dims(np.expand_dims(updatedList[:,i],axis = 1),axis = 0))
            
            print(modelOutput)

            modelPrediction = predDict[np.argmax(modelOutput)]

            predictions.append(modelPrediction)
        
        else:
            
            predictions.append(0)
    
    return predictions, updatedList

#overProvisionedList = 

def getRightOutputs(usageList,minThreshold, maxThreshold):
    
    currList = usageList[0,:]
    print(currList)
    
    target = []
    
    for i in range(usageList.shape[1]):
        if currList[i] > maxThreshold:# Scale Up
            #print("MaxThres ",maxThreshold," ",currList[i])
            target.append(1)
        elif currList[i] < minThreshold: # Scale Down
            #print("MinThres ",minThreshold," ",currList[i])
            target.append(-1)
        else:
            #print("Same ",currList[i])
            target.append(0)  #Remain same
    
    return target

def getVirtualMachineCPU():
    
    availableVirtualMachineCPU = 10
    
    return availableVirtualMachineCPU

def getPercentagesBasedOnPredictions(predictions, usageArray, minThreshold, maxThreshold):
    
    underProvisionedContainers = [i for i in range(usageArray[0,:].shape[1])  if usageArray[0,i]>maxThreshold]
    
    overProvisionedContainers = [i for i in range(usageArray[0,:].shape[1])  if usageArray[0,i]<minThreshold]
    
    rightlyProvisionedContainers = [i for i in range(usageArray[0,:].shape[1])  if usageArray[0,i]>=minThreshold and usageArray[0,i]<=maxThreshold]
    
    availableVCPU = getVirtualMachineCPU()
    
    VCPUSplit = 0
    
    percentArray = np.zeros(len(predictions))
    
    if len(overProvisionedContainers)>0:
        
        availableVCPU = availableVCPU + len(overProvisionedContainers) * 10
        
        for i in overProvisionedContainers:
            
            percentArray[i] = -10
    
    #if len(rightlyProvisioned)>0:
        #availableVCPU = availableVCPU + len(rightlyProvisioned) * 5
        
    if availableVCPU>0 and len(underProvisionedContainers)>0:
        
        if len(underProvisionedContainers)*10>availableVCPU:
            
            for i in rightlyProvisionedContainers:
                
                percentArray[i] = -5
                
                availableVCPU += 5
                
                if (availableVCPU < len(underProvisionedContainers)*10):
                    
                    break
        
            VCPUSplit = availableVCPU/len(underProvisionedContainers)
            
        else:
            
            VCPUSplit = 10
        
        for i in underProvisionedContainers:
                
                percentArray[i] = VCPUSplit
        
    
    return percentArray
        

def callAPIWithPredictions(predictions,URL):

    headers = {
        'Content-Type': 'application/json',
    }

    data = '{"predictions":['+ ','.join(str(num) for num in predictions) +']}'
    print(data)
    response = requests.post(URL, headers=headers, data=data)
    

    
class Prediction():
    def __init__(self, model, maxLengthParam,containerCount,minThreshold, maxThreshold):
        self.usageArray = np.empty(shape = (0,containerCount))
        self.correctOutputArray = np.empty(shape = (0,containerCount))
        self.predictionsArray = np.empty(shape = (0,containerCount))
        self.model = model
        self.maxLengthParam = maxLengthParam
        self.minThreshold = minThreshold
        self.maxThreshold = maxThreshold
        self.lastPredictions = [-1, -1, -1, -1]
    
    def generatePredictions(self): 
        predictions,self.usageArray = getPredictionsForOneTimeStep(self.model,self.usageArray,self.maxLengthParam)       
        self.predictionsArray = appendToList(self.predictionsArray, predictions, self.maxLengthParam)
        if(self.usageArray.shape[0]==self.maxLengthParam):
            correctOutputsList = getRightOutputs(self.usageArray,self.minThreshold, self.maxThreshold)
            self.correctOutputArray = appendToList(self.correctOutputArray, correctOutputsList, self.maxLengthParam)
            print("Last expected Outputs: ",correctOutputsList)  
            print(accuracy_score(self.lastPredictions,correctOutputsList))
            print("Predictions: ",predictions)            
            callAPIWithPredictions(predictions,"http://152.46.16.197:5000/changeVCPU")
            self.lastPredictions = predictions
            
    
# def generatePredictions(model, maxLengthParam,containerCount,minThreshold, maxThreshold):
    
#     usageArray = np.empty(shape = (0,containerCount))
    
#     cnt = 0;
    
#     correctOutputArray = np.empty(shape = (0,containerCount))
    
#     predictionsArray = np.empty(shape = (0,containerCount))
    
#     while cnt<80:
        
#         predictions,usageArray = getPredictionsForOneTimeStep(model,usageArray,maxLengthParam)
        
#         predictionsArray = appendToList(predictionsArray, predictions, maxLengthParam)
        
        
#         if(usageArray.shape[0]==maxLengthParam):
    
#             correctOutputsList = getRightOutputs(usageArray,minThreshold, maxThreshold)

#             correctOutputArray = appendToList(correctOutputArray, correctOutputsList, maxLengthParam)
            
#             print("Predictions: ",predictions)
            
#             print("Expected Outputs: ",correctOutputsList)
            
#             callAPIWithPredictions(predictions,"http://152.46.19.96:5000/changeVCPU")
            
#             print(accuracy_score(predictions,correctOutputsList))
            
#             #percentArray = getPercentagesBasedOnPredictions(predictions,usageArray,minThreshold, maxThreshold)
            
#             #print("Percentage Changes",percentArray)
#             #for i in range(usageArray.shape[1]):

#                 #correctOutputsForTraining = to_categorical(correctOutputs,num_classes = 3)
        
#         cnt+=1

In [6]:
LSTMModel = getTrainedLSTMModel(50)
RLLSTMModel = getTrainedRLLSTM(50)
RL3OutputDNNModel = getTrainedRL3OutputDNN(50)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Returning Trained Model
Returning Trained Model


In [7]:
temp = cpuinfo()
test = Prediction(RLLSTMModel,50,len(temp),30,70)
for i in range(51):
    test.generatePredictions()

[[0.1802526  0.08430745 0.73544   ]]
[[0.04346879 0.01617835 0.9403529 ]]
[[0.06510081 0.02471574 0.9101834 ]]
[[0.03122516 0.02971221 0.93906265]]
[0.6705875 1.8296775 1.3011888 2.4856   ]
Expected Outputs:  [-1, -1, -1, -1]
0.0
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.18541709 0.08797005 0.7266129 ]]
[[0.04305548 0.01604594 0.9408986 ]]
[[0.05909842 0.02272924 0.91817236]]
[[0.03762276 0.03303009 0.92934716]]
[0.6705875 1.8296775 0.7849193 2.4856   ]
Expected Outputs:  [-1, -1, -1, -1]
1.0
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}


In [8]:
sched = BackgroundScheduler()
sched.add_job(test.generatePredictions, 'interval', seconds=2)
sched.start()
print(datetime.datetime.now())

2019-04-24 20:50:43.231784
[[0.18787235 0.08988774 0.72223985]]
[[0.04309245 0.01610332 0.9408043 ]]
[[0.05789914 0.0226151  0.91948575]]
[[0.95424527 0.00896309 0.03679163]]
[0.6705875 1.8296775 0.7849193 2.4856   ]
Expected Outputs:  [-1, -1, -1, -1]
1.0
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.18574244 0.08881096 0.72544664]]
[[0.04322232 0.01617002 0.94060767]]
[[0.05958662 0.02345496 0.91695845]]
[[0.99102366 0.00262504 0.00635125]]
[0.6705875 1.8296775 0.7849193 2.4856   ]
Expected Outputs:  [-1, -1, -1, -1]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.1858162  0.08937113 0.7248127 ]]
[[0.0468926  0.01769559 0.93541175]]
[[0.05992885 0.02350481 0.9165664 ]]
[[0.99205196 0.00250261 0.00544532]]
[0.3587209 1.800837  0.7849193 2.4856   ]
Expected Outputs:  [-1, -1, -1, -1]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.18601935 0.08997969 0.72400093]]
[[0.05299334 0.01996336 0.9270433 ]]
[[0.05728288 0.02230333 0.9204

[[0.16923583 0.07827273 0.7524914 ]]
[[0.05970364 0.02261553 0.91768086]]
[[0.06431016 0.02389733 0.9117925 ]]
[[0.9909837  0.00274568 0.00627053]]
[ 0.6751887  1.8607098  0.9047117 26.6327599]
Expected Outputs:  [-1, -1, -1, -1]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.17073175 0.07919974 0.7500684 ]]
[[0.06656124 0.02478086 0.9086579 ]]
[[0.06523184 0.02423701 0.91053116]]
[[0.9915597  0.00271727 0.005723  ]]
[ 0.6751887  1.8607098  0.9047117 26.6327599]
Expected Outputs:  [-1, -1, -1, -1]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.1738378  0.08113141 0.7450308 ]]
[[0.07159943 0.02616234 0.90223825]]
[[0.06565852 0.02438064 0.90996087]]
[[0.9913018  0.00272908 0.00596908]]
[ 0.6751887  1.8607098  0.9047117 26.6327599]
Expected Outputs:  [-1, -1, -1, -1]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.17655465 0.08282691 0.7406184 ]]
[[0.07122448 0.02559121 0.9031843 ]]
[[0.06628311 0.02459294 0.909124  ]]
[[0.025

[[0.18443221 0.08920299 0.72636485]]
[[0.06627022 0.02366702 0.91006273]]
[[0.06371859 0.02405708 0.91222435]]
[[0.0295904  0.02759027 0.94281936]]
[ 0.6507439  1.3326535  1.3315639 51.3984816]
Expected Outputs:  [-1, -1, -1, 0]
1.0
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.18679427 0.09091294 0.72229284]]
[[0.06328663 0.02278524 0.9139281 ]]
[[0.06409883 0.02409761 0.91180354]]
[[0.9559867  0.0087898  0.03522358]]
[ 0.4434756  1.9208401  1.5260106 28.2395299]
Expected Outputs:  [-1, -1, -1, -1]
1.0
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.18585494 0.09039138 0.7237537 ]]
[[0.06027427 0.02192895 0.91779673]]
[[0.06534126 0.02449584 0.91016287]]
[[0.99085826 0.00276653 0.00637532]]
[ 0.3803563  1.8395696  2.1028569 74.2970171]
Expected Outputs:  [-1, -1, -1, 1]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.18291615 0.08856389 0.7285199 ]]
[[0.05740432 0.0211178  0.9214779 ]]
[[0.06776523 0.02533318 0.90690166]]
[[0.99157

[[0.17919296 0.08531214 0.73549485]]
[[0.05415859 0.02007486 0.9257666 ]]
[[0.0544808  0.02096543 0.9245538 ]]
[[0.9913073  0.00269393 0.00599884]]
[ 0.4040493  1.904911   1.2905509 58.4271743]
Expected Outputs:  [-1, -1, -1, 0]
1.0
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.17967853 0.08579992 0.73452157]]
[[0.052317   0.0195533  0.92812973]]
[[0.05686081 0.02174997 0.9213893 ]]
[[0.02944692 0.02781226 0.94274086]]
[0.5954961 1.8294838 1.9996896 3.4740863]
Expected Outputs:  [-1, -1, -1, -1]
0.75
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.18004346 0.08614758 0.733809  ]]
[[0.05083756 0.01913826 0.9300242 ]]
[[0.05914274 0.02242541 0.9184319 ]]
[[0.02871579 0.02367784 0.9476064 ]]
[ 0.4142569  1.8325257  1.1225378 67.7295671]
Expected Outputs:  [-1, -1, -1, 0]
0.75
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.18073562 0.0866798  0.7325846 ]]
[[0.04973844 0.01883513 0.9314264 ]]
[[0.06022443 0.02261405 0.9171615 ]]
[[0.962697

[[0.176932   0.08333866 0.73972934]]
[[0.05042957 0.01913966 0.9304308 ]]
[[0.06488292 0.02436512 0.91075194]]
[[0.02052037 0.01658017 0.9628995 ]]
[ 0.5467982  1.9018533  1.8169631 10.7276298]
Expected Outputs:  [-1, -1, -1, -1]
0.75
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.1792733  0.08480711 0.73591954]]
[[0.0490202  0.01868906 0.9322907 ]]
[[0.06655315 0.02504751 0.9083993 ]]
[[0.96853113 0.00723371 0.02423517]]
[ 0.7407518  1.8299449  1.3439926 53.9321354]
Expected Outputs:  [-1, -1, -1, 0]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.17816761 0.08410454 0.7377279 ]]
[[0.04796812 0.01835951 0.9336723 ]]
[[0.06544517 0.02457846 0.90997636]]
[[0.9916181  0.0026081  0.00577384]]
[ 0.4699508  1.9539533  1.1765347 19.0362982]
Expected Outputs:  [-1, -1, -1, -1]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.1776703  0.08392127 0.73840845]]
[[0.04733493 0.01817012 0.934495  ]]
[[0.06415576 0.02408774 0.91175646]]
[[0.02

[[0.17033273 0.07947782 0.7501895 ]]
[[0.04806378 0.01851097 0.93342525]]
[[0.07268424 0.02650247 0.9008132 ]]
[[0.9836817  0.00218867 0.01412973]]
[ 0.5445259  1.8012155  0.7092605 87.023402 ]
Expected Outputs:  [-1, -1, -1, 1]
0.75
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.17318942 0.08117893 0.74563164]]
[[0.04726665 0.01821677 0.9345166 ]]
[[0.07420331 0.02707728 0.8987194 ]]
[[0.01872066 0.00799977 0.97327954]]
[ 0.4127793  1.9853752  1.2784411 67.2455408]
Expected Outputs:  [-1, -1, -1, 0]
1.0
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.17402184 0.08155503 0.74442315]]
[[0.0469465  0.01810767 0.9349458 ]]
[[0.07217998 0.02635052 0.90146947]]
[[0.01409214 0.00659448 0.9793133 ]]
[0.7731681 1.8167061 1.5826011 2.944673 ]
Expected Outputs:  [-1, -1, -1, -1]
1.0
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.1782324 0.0842177 0.7375499]]
[[0.04673477 0.01800901 0.93525624]]
[[0.07275582 0.0266774  0.90056676]]
[[0.90563303 0

In [9]:
sched.shutdown() # shutdown the scheduler

[[0.17226997 0.08120137 0.7465286 ]]
[[0.04607503 0.01768712 0.9362379 ]]
[[0.05598264 0.02147081 0.92254657]]
[[0.03638882 0.03193927 0.9316719 ]]
[ 0.3641847  1.8497914  2.5364659 67.4469597]
Expected Outputs:  [-1, -1, -1, 0]
0.75
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}


In [ ]:
mylist = np.array([cpuinfo()])
print(mylist)
print(mylist.shape)

In [ ]:
mylist2 = np.insert(mylist,0, np.array([cpuinfo()]), axis = 0)
print(mylist2)

In [ ]:
mylist = np.append(np.empty(shape = (0,5)), np.array([cpuinfo()]), axis = 0)
print(mylist)
print(mylist.shape)

In [ ]:
mylist[:,1]

In [ ]:
a = [1,2,3,4]
a[1:]
','.join(str(e) for e in a)
print("hey",a[:3])

In [ ]:
b = np.random.randint(1,100,size = (10,5))
b

In [ ]:
np.expand_dims(np.expand_dims(b[:,1],axis = 1),axis = 0).shape
#b[:,1]

In [ ]:
np.zeros(5)