In [1]:
%matplotlib inline
from __future__ import print_function
import numpy as np
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Input
from keras.layers import LSTM, SpatialDropout1D 
from sklearn.model_selection import train_test_split
import csv
import keras
from keras.utils import to_categorical
from keras.callbacks import ModelCheckpoint
import os
#from getcpuinfo import cpuinfo
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import requests
from apscheduler.schedulers.background import BackgroundScheduler
import datetime
from keras import regularizers

Using TensorFlow backend.


In [2]:
import sys, os
sys.path.insert(0, os.path.abspath('..'))
from apis.getcpuinfo import cpuinfo 

In [3]:
from sklearn.metrics import accuracy_score

In [4]:
def getTrainedLSTMModel(maxLengthParam):
    
    model = Sequential()
    
    #model.add(SpatialDropout1D(0.3))
    
    model.add(LSTM((50),dropout = 0.3,batch_input_shape = (None,maxLengthParam,1), return_sequences = True))
    
    model.add(Dense(50, activation = 'tanh'))
    
    #model.add(SpatialDropout1D(0.3))
    
    model.add(LSTM(25,return_sequences = False))
    
    model.add(Dense(3, activation='softmax'))
    
    model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])
    
    if os.path.isfile("LSTMBestWeights.hdf5"):
        
        #print("Hey")
        
        model.load_weights("LSTMBestWeights.hdf5")
        
        return model
    else:
        
        print("Unable to find trained model")
        
        return -1;
    
    
def getTrained3OuptutModel(maxLengthParam):
    
    model = Sequential()
    
    #model.add(SpatialDropout1D(0.3))
    
    model.add(Flatten(batch_input_shape = (None,maxLengthParam,1)))
    
    model.add(Dense(50, activation = "relu"))
    
    model.add(Dropout(0.3, noise_shape=None, seed=None))
    
    model.add(Dense(25, activation = 'relu'))
    
    model.add(Dropout(0.3, noise_shape=None, seed=None))
    
    #model.add(SpatialDropout1D(0.3))
    
    model.add(Dense(12,activation = 'relu'))
    
    model.add(Dropout(0.3, noise_shape=None, seed=None))
    
    model.add(Dense(6,activation = 'relu'))
    
    model.add(Dropout(0.3, noise_shape=None, seed=None))
    
    model.add(Dense(3, activation='softmax'))
    
    model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])
    
    if os.path.isfile("3OutputDNNBestWeights.hdf5"):
        
        #print("Hey")
        
        model.load_weights("3OutputDNNBestWeights.hdf5")
        
        print("Returning Trained Model")
        
        return model
    else:
        
        print("Unable to find trained model")
        
        return -1;
    
def getTrainedRL3OutputDNN(historyParam):
    
    usageInputLayer = keras.layers.Input(shape=(historyParam,1))
    
    flattened_layer = keras.layers.Flatten()(usageInputLayer)
    
    '''fullyConnected_0 = keras.layers.Dense(125, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(flattened_layer)'''
    
    fullyConnected_1 = keras.layers.Dense(50, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(flattened_layer)
    
    #drop1 = keras.layers.Dropout(0.25)(fullyConnected_1)
    
    fullyConnected_2 = keras.layers.Dense(50, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(fullyConnected_1)
    
    #drop2 = keras.layers.Dropout(0.25)(fullyConnected_2)
    
    fullyConnected_3 = keras.layers.Dense(50, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(fullyConnected_2)
    
    fullyConnected_4 = keras.layers.Dense(25, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(fullyConnected_3)
    
    fullyConnected_5 = keras.layers.Dense(12, activation = 'relu',
                    kernel_initializer='he_normal', kernel_regularizer=regularizers.l2(0.1))(fullyConnected_4)
    
    fullyConnected_6 = keras.layers.Dense(6, activation = 'relu',
                    kernel_initializer='he_normal',kernel_regularizer=regularizers.l2(0.1))(fullyConnected_5)
    
    softmax_output = keras.layers.Dense(3,activation='softmax',kernel_initializer='he_normal')(fullyConnected_6)
    
    predictionModel = keras.models.Model(inputs=usageInputLayer,outputs=softmax_output)
    
    if os.path.isfile("3OutputRLV4BestWeights.hdf5"):
        
        #print("Hey")
        
        predictionModel.load_weights("3OutputRLV4BestWeights.hdf5")
        
        print("Returning Trained Model")
        
        return predictionModel
    
    else:
        
        print("Unable to find trained model")
        
        return -1;
    
def getTrainedRLLSTM(historyParam):
    
    usageInputLayer = keras.layers.Input(shape=(historyParam,1))
    
    #flattened_layer = keras.layers.Flatten()(usageInputLayer)
    
    LSTM_1 = keras.layers.LSTM((50), return_sequences = True)(usageInputLayer)
    
    full_connect_2 = keras.layers.Dense(25, activation = 'relu',kernel_initializer='he_normal')(LSTM_1)
    
    LSTM_3 = keras.layers.LSTM(25, return_sequences = False)(full_connect_2)
    
    full_connect_3 = keras.layers.Dense(12, activation = 'relu',kernel_initializer='he_normal')(LSTM_3)
    
    full_connect_4 = keras.layers.Dense(6, activation = 'relu',kernel_initializer='he_normal')(full_connect_3)
    
    softmax_output = keras.layers.Dense(3,activation='softmax',kernel_initializer='he_normal')(full_connect_4)
    
    predictionModel = keras.models.Model(inputs=usageInputLayer,outputs=softmax_output)
    
    if os.path.isfile("LSTMV3RLBestWeights.hdf5"):
        
        #print("Hey")
        
        predictionModel.load_weights("LSTMV3RLBestWeights.hdf5")
        
        print("Returning Trained Model")
        
        return predictionModel
    else:
        
        print("Unable to find trained model")
        
        return -1

In [5]:
def appendToList(oldList,newList,maxLength):
    
    #append to the new entries
    #oldList = np.insert(oldList,0,np.array([newList]),axis = 0)
    oldList = np.append(oldList,np.array([newList]),axis = 0)
    #Remove oldest row if there are more than 50 entries
    if(oldList.shape[0]>maxLength):
        oldList = oldList[1:,:]
    #print(oldList)
    return oldList

def getPredictionsForOneTimeStep(model,usageList,maxLengthParam):
    
    currUsageList = cpuinfo()
    
    updatedList = appendToList(usageList,currUsageList,maxLengthParam)
    
    predictions = []
    
    predDict = {0:0,1:1,2:-1}
    
    for i in range(updatedList.shape[1]):
        
        if updatedList.shape[0]==maxLengthParam:
            
            modelOutput = model.predict(np.expand_dims(np.expand_dims(updatedList[:,i],axis = 1),axis = 0))
            
            print(modelOutput)

            modelPrediction = predDict[np.argmax(modelOutput)]

            predictions.append(modelPrediction)
        
        else:
            
            predictions.append(0)
    
    return predictions, updatedList

#overProvisionedList = 

def getRightOutputs(usageList,minThreshold, maxThreshold):
    
    currList = usageList[0,:]
    print(currList)
    
    target = []
    
    for i in range(usageList.shape[1]):
        if currList[i] > maxThreshold:# Scale Up
            #print("MaxThres ",maxThreshold," ",currList[i])
            target.append(1)
        elif currList[i] < minThreshold: # Scale Down
            #print("MinThres ",minThreshold," ",currList[i])
            target.append(-1)
        else:
            #print("Same ",currList[i])
            target.append(0)  #Remain same
    
    return target

def getVirtualMachineCPU():
    
    availableVirtualMachineCPU = 10
    
    return availableVirtualMachineCPU

def getPercentagesBasedOnPredictions(predictions, usageArray, minThreshold, maxThreshold):
    
    underProvisionedContainers = [i for i in range(usageArray[0,:].shape[1])  if usageArray[0,i]>maxThreshold]
    
    overProvisionedContainers = [i for i in range(usageArray[0,:].shape[1])  if usageArray[0,i]<minThreshold]
    
    rightlyProvisionedContainers = [i for i in range(usageArray[0,:].shape[1])  if usageArray[0,i]>=minThreshold and usageArray[0,i]<=maxThreshold]
    
    availableVCPU = getVirtualMachineCPU()
    
    VCPUSplit = 0
    
    percentArray = np.zeros(len(predictions))
    
    if len(overProvisionedContainers)>0:
        
        availableVCPU = availableVCPU + len(overProvisionedContainers) * 10
        
        for i in overProvisionedContainers:
            
            percentArray[i] = -10
    
    #if len(rightlyProvisioned)>0:
        #availableVCPU = availableVCPU + len(rightlyProvisioned) * 5
        
    if availableVCPU>0 and len(underProvisionedContainers)>0:
        
        if len(underProvisionedContainers)*10>availableVCPU:
            
            for i in rightlyProvisionedContainers:
                
                percentArray[i] = -5
                
                availableVCPU += 5
                
                if (availableVCPU < len(underProvisionedContainers)*10):
                    
                    break
        
            VCPUSplit = availableVCPU/len(underProvisionedContainers)
            
        else:
            
            VCPUSplit = 10
        
        for i in underProvisionedContainers:
                
                percentArray[i] = VCPUSplit
        
    
    return percentArray
        

def callAPIWithPredictions(predictions,URL):

    headers = {
        'Content-Type': 'application/json',
    }

    data = '{"predictions":['+ ','.join(str(num) for num in predictions) +']}'
    print(data)
    response = requests.post(URL, headers=headers, data=data)
    

    
class Prediction():
    def __init__(self, model, maxLengthParam,containerCount,minThreshold, maxThreshold):
        self.usageArray = np.empty(shape = (0,containerCount))
        self.correctOutputArray = np.empty(shape = (0,containerCount))
        self.predictionsArray = np.empty(shape = (0,containerCount))
        self.model = model
        self.maxLengthParam = maxLengthParam
        self.minThreshold = minThreshold
        self.maxThreshold = maxThreshold
        self.lastPredictions = [0, 0, 0, 0]
    
    def generatePredictions(self): 
        predictions,self.usageArray = getPredictionsForOneTimeStep(self.model,self.usageArray,self.maxLengthParam)       
        self.predictionsArray = appendToList(self.predictionsArray, predictions, self.maxLengthParam)
        if(self.usageArray.shape[0]==self.maxLengthParam):
            correctOutputsList = getRightOutputs(self.usageArray,self.minThreshold, self.maxThreshold)
            self.correctOutputArray = appendToList(self.correctOutputArray, correctOutputsList, self.maxLengthParam)
            print("Expected Outputs: ",correctOutputsList)  
            print(accuracy_score(self.lastPredictions,correctOutputsList))
            print("Predictions: ",predictions)            
            callAPIWithPredictions(predictions,"http://152.46.16.197:5000/changeVCPU")
            self.lastPredictions = predictions
            
    
# def generatePredictions(model, maxLengthParam,containerCount,minThreshold, maxThreshold):
    
#     usageArray = np.empty(shape = (0,containerCount))
    
#     cnt = 0;
    
#     correctOutputArray = np.empty(shape = (0,containerCount))
    
#     predictionsArray = np.empty(shape = (0,containerCount))
    
#     while cnt<80:
        
#         predictions,usageArray = getPredictionsForOneTimeStep(model,usageArray,maxLengthParam)
        
#         predictionsArray = appendToList(predictionsArray, predictions, maxLengthParam)
        
        
#         if(usageArray.shape[0]==maxLengthParam):
    
#             correctOutputsList = getRightOutputs(usageArray,minThreshold, maxThreshold)

#             correctOutputArray = appendToList(correctOutputArray, correctOutputsList, maxLengthParam)
            
#             print("Predictions: ",predictions)
            
#             print("Expected Outputs: ",correctOutputsList)
            
#             callAPIWithPredictions(predictions,"http://152.46.19.96:5000/changeVCPU")
            
#             print(accuracy_score(predictions,correctOutputsList))
            
#             #percentArray = getPercentagesBasedOnPredictions(predictions,usageArray,minThreshold, maxThreshold)
            
#             #print("Percentage Changes",percentArray)
#             #for i in range(usageArray.shape[1]):

#                 #correctOutputsForTraining = to_categorical(correctOutputs,num_classes = 3)
        
#         cnt+=1

In [6]:
LSTMModel = getTrainedLSTMModel(50)
RLLSTMModel = getTrainedRLLSTM(50)
RL3OutputDNNModel = getTrainedRL3OutputDNN(50)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Returning Trained Model
Returning Trained Model


In [7]:
temp = cpuinfo()
test = Prediction(RLLSTMModel,50,len(temp),30,70)
for i in range(51):
    test.generatePredictions()

[[0.15672234 0.06539802 0.7778797 ]]
[[0.03893573 0.02136711 0.93969715]]
[[0.03258403 0.01201307 0.95540285]]
[[0.01605302 0.9547015  0.02924551]]
[  0.4632678   0.9759759   3.3820899 107.6126222]
Predictions:  [-1, -1, -1, 1]
{"predictions":[-1,-1,-1,1]}
[[0.15848134 0.06682731 0.7746914 ]]
[[0.04307551 0.02306594 0.9338585 ]]
[[0.03290318 0.01224024 0.9548566 ]]
[[0.01606992 0.95465827 0.02927183]]
[  0.4632678   0.9759759   3.3820899 107.6126222]
Predictions:  [-1, -1, -1, 1]
{"predictions":[-1,-1,-1,1]}


In [8]:
sched = BackgroundScheduler()
sched.add_job(test.generatePredictions, 'interval', seconds=2)
sched.start()
print(datetime.datetime.now())

2019-04-24 20:36:10.120036
[[0.15859397 0.06748793 0.7739181 ]]
[[0.04734706 0.02462927 0.92802364]]
[[0.03188593 0.01173457 0.9563795 ]]
[[0.0160889  0.9546134  0.02929777]]
[  1.2363267   0.9759759   3.3820899 107.6126222]
Predictions:  [-1, -1, -1, 1]
{"predictions":[-1,-1,-1,1]}
[[0.15604547 0.06662817 0.7773264 ]]
[[0.05038233 0.02521227 0.92440534]]
[[0.03256357 0.01218108 0.9552553 ]]
[[0.01609173 0.95460755 0.02930073]]
[  1.2363267   0.9759759   3.3820899 107.6126222]
Predictions:  [-1, -1, -1, 1]
{"predictions":[-1,-1,-1,1]}
[[0.1563779  0.06734633 0.77627575]]
[[0.04639955 0.01986751 0.9337329 ]]
[[0.03217862 0.0119381  0.95588326]]
[[0.01609697 0.9545978  0.02930516]]
[  1.2363267   0.3954032   2.8239442 119.4082242]
Predictions:  [-1, -1, -1, 1]
{"predictions":[-1,-1,-1,1]}
[[0.15531881 0.06717514 0.7775061 ]]
[[0.03498869 0.01744503 0.9475663 ]]
[[0.03099988 0.01142818 0.9575719 ]]
[[0.01610469 0.95458263 0.02931265]]
[  1.2363267   0.3954032   2.8239442 119.4082242]
Pred

[[0.0281896 0.0122548 0.9595556]]
[[0.03485811 0.01559156 0.94955033]]
[[0.05321693 0.01932821 0.9274548 ]]
[[0.12437686 0.81249535 0.06312778]]
[  1.0034749   0.3341175   2.6625711 117.6890467]
Predictions:  [-1, -1, -1, 1]
{"predictions":[-1,-1,-1,1]}
[[0.0298057  0.01280829 0.9573861 ]]
[[0.04016681 0.01764073 0.94219244]]
[[0.05574127 0.02013183 0.9241269 ]]
[[0.21755938 0.7110254  0.07141526]]
[  1.0034749   0.3341175   2.6625711 117.6890467]
Predictions:  [-1, -1, -1, 1]
{"predictions":[-1,-1,-1,1]}
[[0.03162792 0.01333469 0.95503736]]
[[0.04143005 0.01738691 0.94118303]]
[[0.05558243 0.01992679 0.92449087]]
[[0.06732575 0.29466766 0.6380065 ]]
[  1.0034749   0.3341175   2.6625711 114.8530731]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.03389452 0.01405261 0.95205283]]
[[0.04006948 0.01619433 0.9437362 ]]
[[0.05359331 0.01916737 0.9272393 ]]
[[0.20172742 0.59931546 0.19895718]]
[  1.0034749   0.3341175   2.6625711 114.8530731]
Predictions:  [-1, -1, -1, 1]
{"

[[0.08149185 0.03011458 0.8883935 ]]
[[0.04818208 0.01828091 0.93353707]]
[[0.0974712  0.03670285 0.8658259 ]]
[[0.9919546  0.00255361 0.00549179]]
[10.267691   0.851704   2.828227  73.5275107]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.08327357 0.03083517 0.88589126]]
[[0.04739866 0.01802487 0.93457645]]
[[0.09943201 0.03759261 0.86297536]]
[[0.02969306 0.02757581 0.9427311 ]]
[ 8.2409157  0.7672047  4.7456512 73.9682361]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.08480409 0.03146147 0.88373446]]
[[0.04642892 0.01767393 0.9358972 ]]
[[0.09674796 0.03658508 0.8666669 ]]
[[0.02425443 0.02051678 0.95522875]]
[ 7.7886955  0.4399711  1.4543907 89.1439463]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.08613916 0.0320258  0.881835  ]]
[[0.04593173 0.01752198 0.9365463 ]]
[[0.09457216 0.03585102 0.8695769 ]]
[[0.97141874 0.00625695 0.02232438]]
[ 6.0994035  6.315405   2.4486265 78.0640913]
Predictions:  [-1, -1, -1, 0]
{"predictions

[[0.09361862 0.03566437 0.87071705]]
[[0.06301786 0.02389625 0.91308594]]
[[0.10699765 0.04077573 0.8522266 ]]
[[0.9844749  0.00212047 0.01340475]]
[ 1.0343429  2.0156665  0.9870705 58.1135921]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09340442 0.03557112 0.8710244 ]]
[[0.06949134 0.02583201 0.9046767 ]]
[[0.10600481 0.04049508 0.8535001 ]]
[[0.9845583  0.00205567 0.013386  ]]
[1.2319093 1.5755516 1.1789709 2.5881978]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.0930075  0.03541544 0.8715771 ]]
[[0.07623006 0.02783619 0.89593375]]
[[0.10246379 0.03915942 0.85837674]]
[[0.01784746 0.00780025 0.9743523 ]]
[ 1.0202783  0.2547414  0.7490964 86.7754265]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09328883 0.03554047 0.8711707 ]]
[[0.07589672 0.02723975 0.89686346]]
[[0.10336205 0.03969966 0.85693824]]
[[0.92861354 0.00542001 0.06596639]]
[ 1.0468994  0.1989932  1.0539799 22.0920236]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,

[[0.09332331 0.03552641 0.8711503 ]]
[[0.05198419 0.01970039 0.9283154 ]]
[[0.09733073 0.03623401 0.8664353 ]]
[[0.93897676 0.00574076 0.05528244]]
[1.0415938 1.8443306 1.1202461 6.5468305]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09324139 0.03548857 0.87127006]]
[[0.0505797  0.01927558 0.9301447 ]]
[[0.09878907 0.03664947 0.86456144]]
[[0.9824448  0.00235535 0.01519988]]
[ 1.0994844  2.0457063  0.8295355 74.669027 ]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09312955 0.03543939 0.87143105]]
[[0.04930696 0.01886714 0.9318259 ]]
[[0.09933128 0.0368654  0.86380327]]
[[0.0172993  0.00842562 0.9742751 ]]
[1.0887109 1.7831395 0.908944  5.2665009]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09288973 0.03535379 0.87175655]]
[[0.04859712 0.01866433 0.9327385 ]]
[[0.10277227 0.038322   0.8589058 ]]
[[0.0144593  0.00695453 0.9785862 ]]
[ 1.0788726  1.9272356  1.1162146 29.4547278]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,

[[0.09328896 0.0354785  0.8712325 ]]
[[0.0488664  0.01886362 0.93227   ]]
[[0.08957833 0.03441006 0.87601155]]
[[0.01676432 0.00790727 0.97532845]]
[ 1.2077727  1.7826009  0.4195999 50.6668729]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.0706569  0.02684738 0.9024958 ]]
[[0.05492316 0.02111903 0.92395777]]
[[0.09212352 0.03550044 0.8723761 ]]
[[0.9408069  0.00519744 0.05399568]]
[0.9808846 1.9271433 1.189973  2.0872708]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.06315288 0.02524542 0.91160166]]
[[0.06247081 0.02366943 0.9138597 ]]
[[0.09844346 0.03801221 0.86354434]]
[[0.0164244  0.00792969 0.97564584]]
[ 1.048956   1.9279283  1.0868725 46.2766378]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.06743889 0.02772504 0.904836  ]]
[[0.07069037 0.02626651 0.90304315]]
[[0.10234906 0.03933542 0.8583155 ]]
[[0.01527083 0.00737169 0.97735745]]
[ 1.1188508  0.9142223  1.7053852 14.4447478]
Predictions:  [-1, -1, -1, -1]
{"predictions":[

[[0.09276174 0.03547192 0.8717663 ]]
[[0.05496873 0.02068966 0.9243416 ]]
[[0.10309601 0.04031229 0.85659176]]
[[0.86829317 0.015596   0.11611093]]
[  1.1005184   1.782437    1.0568655 101.1024166]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.0925976  0.03539779 0.8720046 ]]
[[0.05315567 0.02015135 0.92669296]]
[[0.10111018 0.03944707 0.8594427 ]]
[[0.02459804 0.01445742 0.9609446 ]]
[ 2.003141   1.9146145  1.2924469 36.1856999]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09282015 0.03547845 0.8717015 ]]
[[0.05152432 0.0196458  0.92882985]]
[[0.10142735 0.03953654 0.85903615]]
[[0.8899902  0.01296965 0.09704021]]
[ 0.290004   1.8542783  1.2218047 52.3012672]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09281638 0.03545188 0.8717317 ]]
[[0.0501952  0.019229   0.93057585]]
[[0.09861626 0.03833522 0.8630485 ]]
[[0.9801215  0.00336763 0.01651083]]
[ 1.1557185  1.8451695  1.0062916 81.0653784]
Predictions:  [-1, -1, -1, 0]
{"predictio

[[0.09482641 0.03614853 0.869025  ]]
[[0.04671941 0.01789746 0.9353832 ]]
[[0.08299123 0.03134929 0.8856595 ]]
[[0.01443341 0.00705869 0.9785079 ]]
[ 1.095248   1.8693177  1.094268  55.1265662]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09350789 0.03564894 0.87084323]]
[[0.04609767 0.01762722 0.93627506]]
[[0.08541717 0.03227562 0.8823072 ]]
[[0.9396592  0.00586088 0.05447989]]
[ 1.0479476  1.8007722  1.0044995 15.4052199]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09328843 0.03560615 0.8711055 ]]
[[0.0471853  0.01808589 0.93472886]]
[[0.08421861 0.03175063 0.8840307 ]]
[[0.9830452  0.00234945 0.01460523]]
[ 1.0301388  1.9403559  1.1909929 83.6840782]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09274055 0.03542179 0.87183774]]
[[0.05198327 0.01996726 0.9280495 ]]
[[0.08411985 0.03169474 0.8841854 ]]
[[0.01710085 0.00824772 0.9746515 ]]
[1.0250081 2.0271079 0.7552524 7.6902496]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1

[[0.0924364  0.03522685 0.87233675]]
[[0.06477112 0.02342019 0.91180867]]
[[0.09637316 0.0364218  0.867205  ]]
[[0.9808004  0.0026583  0.01654132]]
[1.0406856 1.2548867 1.0970812 8.2371914]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09178341 0.03497311 0.87324345]]
[[0.06187736 0.02264822 0.91547436]]
[[0.09702904 0.0365886  0.86638236]]
[[0.9836556  0.00228176 0.01406268]]
[ 1.0479897  1.8408087  0.4042969 42.4932448]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09227888 0.03517878 0.8725423 ]]
[[0.05873066 0.02173242 0.91953695]]
[[0.10141728 0.03835301 0.8602297 ]]
[[0.01824716 0.00905208 0.9727007 ]]
[ 1.0618721  1.9798431  1.0076218 35.9112078]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.0924485  0.03524013 0.8723113 ]]
[[0.05643396 0.02111244 0.9224535 ]]
[[0.1032308  0.03903681 0.85773236]]
[[0.9303157  0.00597616 0.0637082 ]]
[1.1061411 1.7112267 0.9872102 4.6818473]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-

[[0.09512165 0.03612329 0.868755  ]]
[[0.04754656 0.01838226 0.9340711 ]]
[[0.09882756 0.03797718 0.8631953 ]]
[[0.01463664 0.00716745 0.9781959 ]]
[ 0.9818015  1.909462   0.6888793 73.3247304]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09637202 0.03664372 0.8669843 ]]
[[0.04720731 0.01826234 0.9345304 ]]
[[0.09894394 0.03809359 0.8629625 ]]
[[0.3782637  0.01816476 0.60357153]]
[ 1.0373579  1.8460605  1.6097908 55.2467815]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.0965094  0.03665529 0.8668353 ]]
[[0.0463794  0.01789932 0.9357212 ]]
[[0.10215368 0.03939604 0.8584503 ]]
[[0.01523891 0.00635218 0.97840893]]
[1.0394447 1.9052915 1.7302012 2.7584059]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.0962486  0.03655399 0.86719745]]
[[0.04601261 0.01775335 0.936234  ]]
[[0.10310339 0.03969636 0.85720026]]
[[0.9550026  0.0044177  0.04057979]]
[ 1.1390441  1.893262   0.8788542 52.1436443]
Predictions:  [-1, -1, -1, 0]
{"predictions":

[[0.09057001 0.03453972 0.87489027]]
[[0.06917804 0.0246884  0.90613353]]
[[0.0857513  0.03298471 0.881264  ]]
[[0.01735876 0.00837632 0.9742649 ]]
[0.989303  0.4362166 1.4696175 2.3906974]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09064747 0.034542   0.8748105 ]]
[[0.06612234 0.02371529 0.9101624 ]]
[[0.08816985 0.03398268 0.8778475 ]]
[[0.9309657  0.00574511 0.0632892 ]]
[ 1.0266191  0.2024673  1.090914  82.5292972]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.09059238 0.03449853 0.87490904]]
[[0.0624789 0.0226192 0.914902 ]]
[[0.08968326 0.03452744 0.87578934]]
[[0.01621621 0.0076473  0.97613657]]
[1.1091676 1.733714  1.2881083 1.2610871]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09082072 0.03457009 0.87460923]]
[[0.05914126 0.02166284 0.91919583]]
[[0.09286021 0.03561887 0.8715209 ]]
[[0.9406015  0.00548171 0.05391677]]
[1.1942729 1.9959394 0.939763  2.8061466]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}

[[0.09258138 0.03524753 0.8721711 ]]
[[0.0488227  0.01876129 0.93241596]]
[[0.0924678  0.03538256 0.87214965]]
[[0.9360822  0.00537285 0.058545  ]]
[ 1.0812158  1.8688647  0.7594786 99.2379632]
Predictions:  [-1, -1, -1, 0]
{"predictions":[-1,-1,-1,0]}
[[0.0926123  0.03525763 0.87213004]]
[[0.04792997 0.01843652 0.93363345]]
[[0.09053069 0.03440072 0.8750686 ]]
[[0.01620095 0.00769435 0.97610474]]
[1.0771014 1.7557935 1.0975493 1.5139681]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09243694 0.03518175 0.8723813 ]]
[[0.04746226 0.01827877 0.934259  ]]
[[0.08798604 0.03333042 0.8786835 ]]
[[0.01379112 0.00645894 0.9797499 ]]
[ 1.0036075  1.8484889  1.398276  68.2908101]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-1,-1,-1]}
[[0.09320679 0.03548699 0.8713061 ]]
[[0.04669198 0.01796206 0.93534595]]
[[0.08314142 0.03154084 0.88531774]]
[[0.01373145 0.00544174 0.98082685]]
[0.9313685 1.9135124 0.5722131 1.9375344]
Predictions:  [-1, -1, -1, -1]
{"predictions":[-1,-

In [ ]:
sched.shutdown() # shutdown the scheduler

In [ ]:
mylist = np.array([cpuinfo()])
print(mylist)
print(mylist.shape)

In [ ]:
mylist2 = np.insert(mylist,0, np.array([cpuinfo()]), axis = 0)
print(mylist2)

In [ ]:
mylist = np.append(np.empty(shape = (0,5)), np.array([cpuinfo()]), axis = 0)
print(mylist)
print(mylist.shape)

In [ ]:
mylist[:,1]

In [ ]:
a = [1,2,3,4]
a[1:]
','.join(str(e) for e in a)
print("hey",a[:3])

In [ ]:
b = np.random.randint(1,100,size = (10,5))
b

In [ ]:
np.expand_dims(np.expand_dims(b[:,1],axis = 1),axis = 0).shape
#b[:,1]

In [ ]:
np.zeros(5)